version: "3"

networks:
  proxy:
  database:

volumes:
  database-data:

services:
  proxy:
    image: nginx:latest
    depends_on:
      - shopvac
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
  database:
    image: postgres:latest
    volumes:
      - database-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - database
  shopvac:
    build:
      context: ./shopvac
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - /app
    expose:
      - "8080"
    networks:
      - proxy
      - database
