FROM node:18-alpine AS build-env
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
COPY client/package.json ./client/
COPY schema/package.json ./schema/
COPY server/package.json ./server/
RUN yarn --pure-lockfile

# Run schema codegen
COPY ./schema ./schema/
RUN yarn --cwd ./schema run codegen

# Copy everything else
COPY . .
RUN yarn --cwd ./server run db:codegen

# Run pipeline
RUN yarn run prettier \
    && yarn run lint \
    && yarn run stylelint
