version: "3"

networks:
  proxy:
  database:

volumes:
  mongo-data:

services:
  nginx:
    image: nginx:latest
    depends_on:
      - shopvac
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - database
  shopvac:
    build:
      context: ./shopvac
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    volumes:
      - /app
    expose:
      - "8080"
    networks:
      - proxy
      - database
