FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln *.csproj ./
COPY Tests/*.csproj ./Tests/
RUN dotnet restore *.sln

# Copy everything else
COPY . ./

# Run pipeline steps
RUN dotnet test
