on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f Dockerfile.pipeline ./UI
      - run: docker build ./UI
      - run: docker build -f Dockerfile.pipeline ./ShopVac
      - run: docker build ./ShopVac
