on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  commit-message:
    name: semantic-pull-request
    uses: amannn/action-semantic-pull-request@v4.3.0
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build -f ./Dockerfile.pipeline ./
      - run: docker build -f ./Dockerfile.client ./
      - run: docker build -f ./Dockerfile.client-pipeline ./
      - run: docker build -f ./Dockerfile.server ./
      - run: docker build -f ./Dockerfile.server-pipeline ./
