on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  commit-message:
    name: semantic-pull-request
    if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name)
    runs-on: ubuntu-20.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: docker build -f ./Dockerfile.pipeline ./
      - run: docker build -f ./Dockerfile.client ./
      - run: docker build -f ./Dockerfile.client-pipeline ./
      - run: docker build -f ./Dockerfile.server ./
      - run: docker build -f ./Dockerfile.server-pipeline ./
